name = "blinko-ics-calendar-worker"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# 环境变量
[vars]
BLINKO_API_BASE = "https://blinko.folio.cool/api/v1"
SYNC_INTERVAL = "3600"

# KV 命名空间
[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "0af0ca4e3eab462390e0df2b2ba35572"
preview_id = "40c73f4912984866a091654256e48dea"

# 定时任务配置
[triggers]
crons = ["0 * * * *"] # 每小时执行一次

# 环境配置
[env.production]
name = "blinko-ics-calendar-worker-prod"

[env.staging]
name = "blinko-ics-calendar-worker-staging"

# 构建配置（注释掉避免循环）
# [build]
# command = "npm run build:worker"

# 自定义域名配置
[[routes]]
pattern = "todo.folio.cool/*"
zone_name = "folio.cool" 